### ISSUE TITLE
[请求qwen失败]: STRING_IS_BLANK-sessionId不能为空

### ISSUE THREAD

**Issue by copper202310** [LLM-Red-Team/qwen-free-api#17]
项目非常不错，有时会出现这个错误
APIException [Error]: [请求qwen失败]: STRING_IS_BLANK-sessionId不能为空
  at checkResult (file:///dist/index.js:1380:9)
  at removeConversation (file:///dist/index.js:1154:3)
 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errcode: -2001,
 errmsg: '[请求qwen失败]: STRING_IS_BLANK-sessionId不能为空',
 data: undefined,
 httpStatusCode: undefined
}

**Comment by Vinlic** [comment]
如果遇到内容审查不通过的会话，session可能直接被千问自动移除，将导致free-api侧的清理会话失败，可以忽略此消息。
